"""User interface text strings and i18n management for LayoutKeep.

Kullanıcı arayüzünde gösterilen tüm çok dilli metinlerin merkezi tanım ve yönetim dosyası.
"""

from __future__ import annotations

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "tr": {
        "GLOSSARY_TITLE": "Terim sözlüğü",
        "GLOSSARY_SOURCE": "Kaynak terim",
        "GLOSSARY_TARGET": "Hedef terim",
        "GLOSSARY_ADD": "Satır ekle",
        "GLOSSARY_SUGGEST": "Belgeden öner",
        "GLOSSARY_SUGGEST_TIP": "Seçili belgede sık geçen terim adaylarını boş hedef hücreleriyle ekler; çevirilerini siz yazarsınız.",
        "GLOSSARY_SUGGEST_NONE": "Öneri için belge seçilmeli (çeviri kurulumundaki dosya kullanılır).",
        "GLOSSARY_SUGGEST_READING": "Belge okunuyor…",
        "GLOSSARY_SUGGEST_ADDED": "{count} aday eklendi — hedef sütununu doldurun.",
        "GLOSSARY_SUGGEST_EMPTY": "Yeni aday bulunamadı (ya hepsi sözlükte ya da yeterince tekrar yok).",
        "GLOSSARY_REMOVE": "Seçili satırı sil",
        "GLOSSARY_LOAD": "Dosyadan yükle…",
        "GLOSSARY_SAVE": "Farklı kaydet…",
        "GLOSSARY_CAPTION": "Sözlük her isteğin istemine eklenir ve çıktıda kullanılıp kullanılmadığı denetlenir; kullanılmayan terim inceleme kuyruğuna düşer. Boş kaynak terimli satırlar yok sayılır.",
        "GLOSSARY_TABLE_TIP": "Çift tıklayıp düzenle; satır ekle/sil ile listeyi büyüt.",
        "GLOSSARY_BAD_FILE": "Dosya bir JSON nesnesi değil: {\"kaynak terim\": \"hedef terim\"} bekleniyor.",
        "GLOSSARY_EDIT": "Düzenle…",
        "BAR_TOGGLE": "Küçük pencereye geç",
        "BAR_TOGGLE_HINT": "Pencereyi gizler, ilerleme yüzen çubukta devam eder; çubuktaki “Pencereye dön” ile geri gelirsin.",
        "HELP_TITLE": "Yardım",
        "TWEAKS_BROWSE": "Gözat…",
        "TWEAKS_GLOSSARY_TIP": "JSON sözlük dosyası seç: {\"kaynak terim\": \"hedef terim\"}",
        "TWEAKS_GLOSSARY_FILTER": "Sözlük (*.json *.csv *.tsv *.txt);;JSON (*.json);;Tablo (*.csv *.tsv);;Tüm dosyalar (*)",
        "WELCOME_SHOW": "Karşılamayı göster",
        "FLOAT_FOLD": "Küçült (sayfanın önünden çekil)",
        "FLOAT_EXPAND": "Geri büyüt",
        "STATUS_VERIFYING": "Çıktı doğrulanıyor…",
        "STATUS_CANCELLED": "İptal edildi",
        "FLOAT_WAITING": "Hazırlanıyor…",
        "FLOAT_PAUSE": "Duraklat",
        "FLOAT_RESUME": "Devam et",
        "FLOAT_RESTORE": "Pencereye dön",
        "FLOAT_DONE": "Bitti",
        "FLOAT_FAILED": "Başarısız",
        "FLOAT_SEGMENTS": "{done}/{total} parça",
        "MENU_RENAME_GROUP": "Grubu yeniden adlandır",
        "MENU_UNGROUP_ALL": "Grubu dağıt",
        "MENU_LEAVE_GROUP": "Gruptan çıkar",
        "SAVE_BTN": "Kaydet",
        "FETCH_MODELS_BTN": "Modelleri Getir",
        "OPTIONAL_NO_KEY_NEEDED": "opsiyonel - LM Studio/Ollama gerektirmez",
        "TIMEOUT_AUTO": "boş = otomatik (öneriliyor)",
                        "DEFAULT_PROFILE_NAME": "Standard",
        "MENU_TEST_CONNECTION": "Bağlantıyı sına",
        "MENU_DELETE": "Sil",
        "APP_TITLE": "LayoutKeep",
        "APP_SUBTITLE": "Düzen Koruyan Belge ve E-Kitap Çevirmeni",
        "THEME_TOGGLE": "Temayı Değiştir",
        "LIGHT_MODE": "Açık Tema",
        "DARK_MODE": "Koyu Tema",
        "UI_LANG_LABEL": "Arayüz Dili",
        "STEP_SETUP": "1. Belge & Format",
        "SETTINGS_CARD_TITLE": "Belge Ayarları",
        "STEP_PROGRESS": "2. Çeviri Süreci",
        "STEP_REVIEW": "3. Tamamlandı",
        "INPUT_FILE_LABEL": "Girdi Dosyası",
        "OUTPUT_FILE_LABEL": "Çıktı Dosyası",
        "OUTPUT_FORMAT_LABEL": "Çıktı Formatı",
        "SOURCE_LANG_LABEL": "Kaynak Dil",
        "TARGET_LANG_LABEL": "Hedef Dil",
        "LANGS_LABEL": "Diller",
        "PROVIDER_LABEL": "Çeviri Sağlayıcısı",
        "PROVIDER_SETTINGS_BTN": "Sağlayıcı Ayarları…",
        "OPEN_OUTPUT_BTN": "Çıktıyı Aç",
        "SHOW_IN_FOLDER_BTN": "Klasörde Göster",
        "BACK_TO_SETUP_BTN": "Yeni Çeviri",
        "OUTPUT_MISSING": "Çıktı dosyası bulunamadı:",
        "OUTPUT_READY": "Çıktı:",
        "START_TRANSLATION_BTN": "Çeviriyi Başlat",
        "COMPLETION_TITLE": "Çeviri Tamamlandı",
        "TWEAKS_TITLE": "Gelişmiş Ayarlar",
        "PROFILE_LABEL": "Hazır ayar",
        "PROFILE_CUSTOM": "Özel (elle ayarlanmış)",
        "PROFILE_DRAFT": "Hızlı taslak (7 istek, daha küçük punto)",
        "PROFILE_QUALITY": "Yayın kalitesi (2 istek, ölçülmüş eşikler)",
        "PROFILE_HINT": "Hazır ayar birkaç değeri birlikte değiştirir; sonrasında tek tek düzenleyebilirsiniz. Çalışan bir koşu başladığı değerleri korur — ama parça parça koşan komut satırı işlerinde her yeni parça değerleri yeniden okur, o yüzden uzun bir koşu sürerken değiştirmeyin.",
        "TWEAKS_TAB_BASIC": "Genel",
        "TWEAKS_TAB_ADVANCED": "Geliştirici",
        "TWEAKS_RESET": "Varsayılanlara Dön",
        "TWEAKS_MENU": "Gelişmiş Ayarlar…",
        "TWEAKS_FOOTER": "Değişiklikler hemen geçerli olur; uygulamayı yeniden başlatmanız gerekmez. Süren bir çeviri başladığı değerlerle devam eder.",
        "TWEAKS_ADVANCED_BANNER": "Buradaki değerler yanlış ayarlandığında hata vermez - çıktıyı sessizce kötüleştirir. Her birinin altında neyin bozulacağı yazıyor.",
        "ERR_NO_API_KEY": "DeepL için API anahtarı gerekli. Sağlayıcı Ayarları'ndan girin (ücretsiz anahtarlar ':fx' ile biter).",
        "STATUS_PAUSING": "duraklatılıyor… (süren istek bitince)",
        "STATUS_PAUSED": "duraklatıldı",
        "STATUS_RESUMING": "çeviriye devam ediliyor…",
        "PROGRESS_FLAGS": "{count} segment işaretlendi",
        "ETA_CALCULATING": "Hesaplanıyor…",
        "ETA_ALMOST": "Tamamlanmak üzere",
        "ETA_MEASURING": "Ölçülüyor…",
        "ETA_SECONDS": "~{s} sn kaldı",
        "ETA_MINUTES": "~{m} dk {s} sn",
        "ETA_MINUTES_ONLY": "~{m} dk",
        "ETA_HOURS": "~{h} sa {m} dk",
        "ETA_HOURS_ONLY": "~{h} sa",
        "ETA_SPEED": "~{v} kar/sn",
        "PROGRESS_SEGMENTS": "{done}/{total} segment çevrildi (%{pct})",
        "PROGRESS_MEMORY_HITS": "TM isabet: {hits}/{total} ({rate})",
        "PROGRESS_BATCH_LIMIT": "Beklenen üst sınır: {s}s",
        "ERROR_TIMEOUT": "Sunucu ({url}) {s} saniye içinde yanıt vermedi.\nBüyük bir yerel model yüklenmesi dakikalar sürebilir; sunucu tamamen hazır olduktan sonra tekrar deneyin, ya da Sağlayıcı Ayarları'ndan zaman aşımını elle yükseltin.",
        "ERROR_CONNECTION": "{url} adresine ulaşılamıyor: {exc}\nLM Studio (1234 portu) veya Ollama (11434 portu) sunucusunun çalıştığından ve sunucu modunun etkin olduğundan emin olun.",
        "ERROR_NO_TEXT": "Belgede çevrilebilir metin bulunamadı.",
        "STATUS_REPEATS_UNIFIED": "{n} tekrarlanan segment aynı kaynak için tek çeviriye getirildi",
        "REVIEW_FIT_FAILED": "çeviri kutuya sığmadı, küçültme yetmedi",
        "PROGRESS_PREVIEW_SOURCE": "Kaynak",
        "PROGRESS_PREVIEW_TARGET": "Çeviri",
        "COMPLETION_STATS_TITLE": "Proses",
        "COMPLETION_OUTPUT_TITLE": "Çıktı Dosyası",
        "COMPLETION_SEGMENTS": "{done} / {total} segment çevrildi (%{pct})",
        "COMPLETION_SPEED": "Ortalama hız: {speed} kar/sn",
        "COMPLETION_FIDELITY": "Düzen uyumu: %{pct}",
        "COMPLETION_DURATION": "Toplam süre: {duration}",
        "COMPLETION_FLAGGED": "{count} segment gözden geçirilmeli",
        "REVIEW_BOX_CRUSHED": "kutu sonraki bloğa değmesin diye kısaltıldı; metin bu kutuya sığmıyor",
        "COMPLETION_FLAGGED_BOX": "bunların {count} tanesi kutu kısaltmasından (metin değil)",
        "COMPLETION_VERIFY_CLEAN": "Doğrulama: çıktıda kayıp bulunmadı",
        "COMPLETION_VERIFY_REPAIRED": "Doğrulama: {count} segment yeniden sorularak düzeltildi",
        "COMPLETION_VERIFY_REMAINING": "Doğrulama: {count} kayıp inceleme için işaretlendi ({kinds})",
        "VERIFY_L1": "sayfa sayısı farklı",
        "VERIFY_L2": "çevrilmeden kaldı",
        "VERIFY_L3": "sayfaya yazılamadı",
        "VERIFY_L4": "sayfa dışına taştı",
        "VERIFY_L5": "etiket sızdı",
        "VERIFY_L6": "sayılar kayboldu",
        "VERIFY_L7": "başka metnin üstüne yazıldı",
        "VERIFY_L8": "çevrilmeyen metin yer değiştirdi",
        "VERIFY_L9": "başka alfabeden harf karıştı",
        "COMPLETION_SUBTITLE": "Belgeniz başarıyla çevrildi. Çıktıyı açabilir, klasörde gösterebilir veya yeni bir çeviri başlatabilirsiniz.",
        "BROWSE_BTN": "Gözat…",
        "DROPZONE_PROMPT": "Dosyayı buraya sürükleyin veya gözatarak seçin",
        "DROPZONE_HINT": "Desteklenenler: PDF, EPUB, DOCX, PNG, JPG, WEBP, LKPROJ",
        "DROPZONE_FILE_SELECTED": "Seçilen dosya:",
        "DROPZONE_CLEAR": "Kaldır",
        "EPUB_LOCK_REASON": "Bu kaynak formatından EPUB çıktısı henüz ölçülüp doğrulanmadı",
        "DOCX_LOCK_REASON": "Bu kaynak formatından Word çıktısı henüz ölçülüp doğrulanmadı",
        "HTML_LOCK_REASON": "Bu kaynak formatından HTML çıktısı henüz ölçülüp doğrulanmadı",
        "IMAGE_LOCK_REASON": "Bu kaynak formatından görsel çıktı henüz ölçülüp doğrulanmadı",
        "LOCKED_SUFFIX": "kilitli",
        "LOCKED_TITLE": "Bu dönüşüm henüz hazır değil",
        "LOCKED_BODY": "Açık çiftler: PDF→PDF/Word/EPUB/HTML, EPUB→EPUB/Word/HTML/PNG, Word→Word/EPUB/HTML/PNG/PDF, PNG→Word. Diğer hedefler ölçüldü ve belge içeriğinin bir kısmını sessizce kaybediyor; hazır olduklarında açılacaklar.\n\nÖlçümler: docs/ENGINE-ARCHITECTURE.md",
        "LOCKED_SOURCE_BODY": "Bu dosya türünden şu an açık hedef yok. Açık çiftler: PDF→PDF/Word/EPUB/HTML, EPUB→EPUB/Word/HTML/PNG, Word→Word/EPUB/HTML/PNG/PDF, PNG→Word.\n\nÖlçümler: docs/ENGINE-ARCHITECTURE.md",
        "FORMAT_SAME": "Kaynak Format ile Aynı",
        "FORMAT_PDF": "PDF Belgesi (.pdf)",
        "FORMAT_HTML": "HTML Web Sayfası (.html)",
        "FORMAT_EPUB": "EPUB E-Kitap (.epub)",
        "FORMAT_DOCX": "Word Belgesi (.docx)",
        "FORMAT_PNG": "PNG Görsel (.png)",
        "FORMAT_JPG": "JPG Görsel (.jpg)",
        "RANGE_LABEL": "Aralık",
        "RANGE_ALL": "Tüm Belge",
        "RANGE_CUSTOM": "Sayfa / Bölüm Aralığı",
        "RANGE_PLACEHOLDER": "Örn: 1-5, 8",
        "RANGE_HINT": "Yalnız bu aralık çevrilir ve çıktı yalnız bu sayfaları içerir (proje tüm belgeyi saklar).",
        "DUAL_LABEL": "Çift dilli PDF",
        "DUAL_OFF": "Kapalı",
        "DUAL_SIDE": "Yan yana (kaynak solda)",
        "DUAL_ALTERNATE": "Almaşık sayfalar",
        "DUAL_HINT": "Çevrilmiş dosyanın yanına, kaynağı da içeren ikinci bir PDF yazılır. Denetim ve asıl çıktı değişmez.",
        "CLOSE_BTN": "Kapat",
        "PROGRESS_TITLE": "Çeviri İşleniyor…",
        "STATUS_READING": "Belge okunuyor ve ayrıştırılıyor…",
        "STATUS_TRANSLATING": "Metinler çevriliyor…",
        "STATUS_FITTING": "Tipografi ve yerleşim hesaplanıyor…",
        "STATUS_WRITING": "Çıktı dosyası kaydediliyor…",
        "STATUS_FINISHED": "İşlem başarıyla tamamlandı!",
        "CANCEL_BTN": "İptal Et",
        "PAUSE_BTN": "Duraklat",
        "RESUME_BTN": "Devam Et",
        "MEMORY_STATS_LABEL": "Bellek Durumu:",
        "PROGRESS_ELAPSED": "Geçen:",
        "PROGRESS_REMAINING": "Kalan:",
        "PROGRESS_SPEED": "Hız:",
        "PROGRESS_MODEL_LABEL": "Aktif Model:",
        "PROGRESS_ACTIVE_TITLE": "İşlenen Segment:",
        "PROGRESS_CHARS_LABEL": "Karakter:",
        "PROGRESS_SEGMENTS_LABEL": "Segment:",
        "PROGRESS_MEMORY_SAVED": "TM Tasarrufu:",
        "PROGRESS_WAITING_SERVER": "Model yanıtı bekleniyor…",
        "PROGRESS_STARTING": "Başlatılıyor…",
        "PROGRESS_PAUSED": "Duraklatıldı",
        "PROGRESS_RESUMING": "Devam ediliyor…",
        "PROGRESS_CANCELLED": "İptal edildi",
        "ERR_MISSING_INPUT": "Girdi dosyası seçilmedi.",
        "ERR_INPUT_NOT_FOUND": "Girdi dosyası bulunamadı:\n",
        "ERR_MISSING_OUTPUT": "Çıktı dosyası belirtilmedi.",
        "ERR_OUTPUT_DIR_NOT_FOUND": "Çıktı klasörü bulunamadı:\n",
        "ERR_NO_MODEL": "Sağlayıcı için model seçilmedi. Ayarlardan model belirleyin.",
        "ERR_INCOMPLETE_INFO": "Eksik Bilgi",
    },
    "en": {
        "GLOSSARY_TITLE": "Glossary",
        "GLOSSARY_SOURCE": "Source term",
        "GLOSSARY_TARGET": "Target term",
        "GLOSSARY_ADD": "Add row",
        "GLOSSARY_SUGGEST": "Suggest from document",
        "GLOSSARY_SUGGEST_TIP": "Adds term candidates that recur in the selected document, with empty target cells for you to fill in.",
        "GLOSSARY_SUGGEST_NONE": "Pick a document first (the one in the job setup is used).",
        "GLOSSARY_SUGGEST_READING": "Reading the document…",
        "GLOSSARY_SUGGEST_ADDED": "{count} candidates added — fill in the target column.",
        "GLOSSARY_SUGGEST_EMPTY": "No new candidates (all already in the glossary, or too few repeats).",
        "GLOSSARY_REMOVE": "Remove selected",
        "GLOSSARY_LOAD": "Load from file…",
        "GLOSSARY_SAVE": "Save as…",
        "GLOSSARY_CAPTION": "The glossary is added to every request and checked in the output; a term that was not used lands in the review queue. Rows without a source term are ignored.",
        "GLOSSARY_TABLE_TIP": "Double-click to edit; add and remove rows to build the list.",
        "GLOSSARY_BAD_FILE": "That file is not a JSON object: {\"source term\": \"target term\"} expected.",
        "GLOSSARY_EDIT": "Edit…",
        "BAR_TOGGLE": "Switch to the compact bar",
        "BAR_TOGGLE_HINT": "Hides the window and keeps the run in the floating bar; “Back to window” on the bar brings it back.",
        "HELP_TITLE": "Help",
        "TWEAKS_BROWSE": "Browse…",
        "TWEAKS_GLOSSARY_TIP": "Pick a JSON glossary file: {\"source term\": \"target term\"}",
        "TWEAKS_GLOSSARY_FILTER": "Glossary (*.json *.csv *.tsv *.txt);;JSON (*.json);;Table (*.csv *.tsv);;All files (*)",
        "WELCOME_SHOW": "Show the welcome screen",
        "FLOAT_FOLD": "Fold away",
        "FLOAT_EXPAND": "Expand",
        "STATUS_VERIFYING": "Verifying the output…",
        "STATUS_CANCELLED": "Cancelled",
        "FLOAT_WAITING": "Preparing…",
        "FLOAT_PAUSE": "Pause",
        "FLOAT_RESUME": "Resume",
        "FLOAT_RESTORE": "Back to window",
        "FLOAT_DONE": "Done",
        "FLOAT_FAILED": "Failed",
        "FLOAT_SEGMENTS": "{done}/{total} segments",
        "MENU_RENAME_GROUP": "Rename group",
        "MENU_UNGROUP_ALL": "Break up group",
        "MENU_LEAVE_GROUP": "Take out of group",
        "MENU_TEST_CONNECTION": "Test connection",
        "MENU_DELETE": "Delete",
        "APP_TITLE": "LayoutKeep",
        "APP_SUBTITLE": "Layout-Preserving Document & E-Book Translator",
        "THEME_TOGGLE": "Toggle Theme",
        "LIGHT_MODE": "Light Mode",
        "DARK_MODE": "Dark Mode",
        "UI_LANG_LABEL": "UI Language",
        "STEP_SETUP": "1. Document & Format",
        "SETTINGS_CARD_TITLE": "Document Settings",
        "STEP_PROGRESS": "2. Translation Progress",
        "STEP_REVIEW": "3. Completed",
        "INPUT_FILE_LABEL": "Input File",
        "OUTPUT_FILE_LABEL": "Output File",
        "OUTPUT_FORMAT_LABEL": "Output Format",
        "SOURCE_LANG_LABEL": "Source Language",
        "TARGET_LANG_LABEL": "Target Language",
        "LANGS_LABEL": "Languages",
        "PROVIDER_LABEL": "Translation Provider",
        "PROVIDER_SETTINGS_BTN": "Provider Settings…",
        "OPEN_OUTPUT_BTN": "Open Output",
        "SHOW_IN_FOLDER_BTN": "Show in Folder",
        "BACK_TO_SETUP_BTN": "New Translation",
        "OUTPUT_MISSING": "Output file not found:",
        "OUTPUT_READY": "Output:",
        "START_TRANSLATION_BTN": "Start Translation",
        "COMPLETION_TITLE": "Translation Completed",
        "TWEAKS_TITLE": "Advanced Settings",
        "PROFILE_LABEL": "Preset",
        "PROFILE_CUSTOM": "Custom (edited by hand)",
        "PROFILE_DRAFT": "Fast draft (7 requests, smaller type)",
        "PROFILE_QUALITY": "Publication quality (2 requests, measured thresholds)",
        "PROFILE_HINT": "A preset moves several values together; you can edit any of them afterwards. A running job keeps the values it started with - but a chunked command-line run reads them again for every new chunk, so do not change them while a long run is going.",
        "TWEAKS_TAB_BASIC": "General",
        "TWEAKS_TAB_ADVANCED": "Developer",
        "TWEAKS_RESET": "Restore Defaults",
        "TWEAKS_MENU": "Advanced Settings…",
        "TWEAKS_FOOTER": "Changes take effect immediately; no restart needed. A job already running keeps the values it started with.",
        "TWEAKS_ADVANCED_BANNER": "A wrong value here does not raise an error - it quietly makes the output worse. Each entry says what breaks.",
        "ERR_NO_API_KEY": "DeepL needs an API key. Enter it in Provider Settings (free keys end in ':fx').",
        "STATUS_PAUSING": "pausing… (after the current request)",
        "STATUS_PAUSED": "paused",
        "STATUS_RESUMING": "resuming…",
        "PROGRESS_FLAGS": "{count} segments flagged",
        "ETA_CALCULATING": "Calculating…",
        "ETA_ALMOST": "Almost done",
        "ETA_MEASURING": "Measuring…",
        "ETA_SECONDS": "~{s}s left",
        "ETA_MINUTES": "~{m}m {s}s",
        "ETA_MINUTES_ONLY": "~{m}m",
        "ETA_HOURS": "~{h}h {m}m",
        "ETA_HOURS_ONLY": "~{h}h",
        "ETA_SPEED": "~{v} chars/s",
        "PROGRESS_SEGMENTS": "{done}/{total} segments translated ({pct}%)",
        "PROGRESS_MEMORY_HITS": "Memory hits: {hits}/{total} ({rate})",
        "PROGRESS_BATCH_LIMIT": "Expected upper bound: {s}s",
        "ERROR_TIMEOUT": "The server ({url}) did not answer within {s} seconds.\nLoading a large local model can take minutes; try again once the server is fully ready, or raise the timeout in Provider Settings.",
        "ERROR_CONNECTION": "{url} cannot be reached: {exc}\nMake sure the LM Studio (port 1234) or Ollama (port 11434) server is running and that its server mode is enabled.",
        "ERROR_NO_TEXT": "No translatable text was found in the document.",
        "STATUS_REPEATS_UNIFIED": "{n} repeated segments were unified into one translation per source",
        "REVIEW_FIT_FAILED": "the translation did not fit its box, and shrinking was not enough",
        "PROGRESS_PREVIEW_SOURCE": "Source",
        "PROGRESS_PREVIEW_TARGET": "Translation",
        "COMPLETION_STATS_TITLE": "Process",
        "COMPLETION_OUTPUT_TITLE": "Output file",
        "COMPLETION_SEGMENTS": "{done} / {total} segments translated ({pct}%)",
        "COMPLETION_SPEED": "Average speed: {speed} chars/s",
        "COMPLETION_FIDELITY": "Layout fidelity: {pct}%",
        "COMPLETION_DURATION": "Total time: {duration}",
        "COMPLETION_FLAGGED": "{count} segments need review",
        "REVIEW_BOX_CRUSHED": "the box was shortened to clear the next block; the text cannot fit it",
        "COMPLETION_FLAGGED_BOX": "{count} of them are shortened boxes, not long text",
        "COMPLETION_VERIFY_CLEAN": "Verification: no losses found in the output",
        "COMPLETION_VERIFY_REPAIRED": "Verification: {count} segments mended by asking again",
        "COMPLETION_VERIFY_REMAINING": "Verification: {count} losses flagged for review ({kinds})",
        "VERIFY_L1": "page count differs",
        "VERIFY_L2": "left untranslated",
        "VERIFY_L3": "not written to the page",
        "VERIFY_L4": "drawn off the page",
        "VERIFY_L5": "markup leaked",
        "VERIFY_L6": "numbers lost",
        "VERIFY_L7": "drawn over other text",
        "VERIFY_L8": "untranslated text moved",
        "VERIFY_L9": "letters from another alphabet",
        "COMPLETION_SUBTITLE": "Your document was translated successfully. Open the output, show it in a folder, or start a new translation.",
        "BROWSE_BTN": "Browse…",
        "DROPZONE_PROMPT": "Drag & drop a file here or browse to select",
        "DROPZONE_HINT": "Supported: PDF, EPUB, DOCX, PNG, JPG, WEBP, LKPROJ",
        "DROPZONE_FILE_SELECTED": "Selected file:",
        "DROPZONE_CLEAR": "Clear",
        "EPUB_LOCK_REASON": "EPUB output from this source format is not yet measured and verified",
        "DOCX_LOCK_REASON": "Word output from this source format is not yet measured and verified",
        "HTML_LOCK_REASON": "HTML output from this source format is not yet measured and verified",
        "IMAGE_LOCK_REASON": "Image output from this source format is not yet measured and verified",
        "LOCKED_SUFFIX": "locked",
        "LOCKED_TITLE": "This conversion is not ready",
        "LOCKED_BODY": "Open pairs: PDF→PDF/Word/EPUB/HTML, EPUB→EPUB/Word/HTML/PNG, Word→Word/EPUB/HTML/PNG/PDF, PNG→Word. The other targets were measured and quietly lose part of the document; they open again once they hold up.\n\nThe measurements: docs/ENGINE-ARCHITECTURE.md",
        "LOCKED_SOURCE_BODY": "No target is open for this file type yet. Open pairs: PDF→PDF/Word/EPUB/HTML, EPUB→EPUB/Word/HTML/PNG, Word→Word/EPUB/HTML/PNG/PDF, PNG→Word.\n\nThe measurements: docs/ENGINE-ARCHITECTURE.md",
        "FORMAT_SAME": "Same as Source",
        "FORMAT_PDF": "PDF Document (.pdf)",
        "FORMAT_HTML": "HTML Webpage (.html)",
        "FORMAT_EPUB": "EPUB E-Book (.epub)",
        "FORMAT_DOCX": "Word Document (.docx)",
        "FORMAT_PNG": "PNG Image (.png)",
        "FORMAT_JPG": "JPG Image (.jpg)",
        "RANGE_LABEL": "Range",
        "RANGE_ALL": "Whole Document",
        "RANGE_CUSTOM": "Page / Section Range",
        "RANGE_PLACEHOLDER": "e.g. 1-5, 8",
        "RANGE_HINT": "Only this range is translated, and the output holds only these pages (the project keeps the whole document).",
        "DUAL_LABEL": "Bilingual PDF",
        "DUAL_OFF": "Off",
        "DUAL_SIDE": "Side by side (source left)",
        "DUAL_ALTERNATE": "Alternating pages",
        "DUAL_HINT": "A second PDF is written beside the translated file, holding the source as well. The audit and the main output are unchanged.",
        "CLOSE_BTN": "Close",
        "PROGRESS_TITLE": "Translating Document…",
        "STATUS_READING": "Reading and parsing document…",
        "STATUS_TRANSLATING": "Translating text segments…",
        "STATUS_FITTING": "Calculating typography and fitting…",
        "STATUS_WRITING": "Saving output file…",
        "STATUS_FINISHED": "Process completed successfully!",
        "CANCEL_BTN": "Cancel",
        "PAUSE_BTN": "Pause",
        "RESUME_BTN": "Resume",
        "MEMORY_STATS_LABEL": "Translation Memory:",
        "PROGRESS_ELAPSED": "Elapsed:",
        "PROGRESS_REMAINING": "Remaining:",
        "PROGRESS_SPEED": "Speed:",
        "PROGRESS_MODEL_LABEL": "Active Model:",
        "PROGRESS_ACTIVE_TITLE": "Active Segment:",
        "PROGRESS_CHARS_LABEL": "Characters:",
        "PROGRESS_SEGMENTS_LABEL": "Segments:",
        "PROGRESS_MEMORY_SAVED": "TM Savings:",
        "PROGRESS_WAITING_SERVER": "Waiting for model response…",
        "PROGRESS_STARTING": "Starting…",
        "PROGRESS_PAUSED": "Paused",
        "PROGRESS_RESUMING": "Resuming…",
        "PROGRESS_CANCELLED": "Cancelled",
        "ERR_MISSING_INPUT": "No input file selected.",
        "ERR_INPUT_NOT_FOUND": "Input file not found:\n",
        "ERR_MISSING_OUTPUT": "No output file specified.",
        "ERR_OUTPUT_DIR_NOT_FOUND": "Output folder not found:\n",
        "ERR_NO_MODEL": "No model selected for provider. Please select a model in settings.",
        "ERR_INCOMPLETE_INFO": "Incomplete Information",
    },
    "de": {
        "GLOSSARY_TITLE": "Glossar",
        "GLOSSARY_SOURCE": "Quellbegriff",
        "GLOSSARY_TARGET": "Zielbegriff",
        "GLOSSARY_ADD": "Zeile hinzufügen",
        "GLOSSARY_SUGGEST": "Aus Dokument vorschlagen",
        "GLOSSARY_SUGGEST_TIP": "Fügt wiederkehrende Begriffe aus dem gewählten Dokument mit leeren Zielzellen hinzu.",
        "GLOSSARY_SUGGEST_NONE": "Zuerst ein Dokument wählen (das aus der Auftragseinrichtung wird verwendet).",
        "GLOSSARY_SUGGEST_READING": "Dokument wird gelesen…",
        "GLOSSARY_SUGGEST_ADDED": "{count} Vorschläge hinzugefügt — Zielspalte ausfüllen.",
        "GLOSSARY_SUGGEST_EMPTY": "Keine neuen Vorschläge (alle schon im Glossar oder zu wenige Wiederholungen).",
        "GLOSSARY_REMOVE": "Ausgewählte löschen",
        "GLOSSARY_LOAD": "Aus Datei laden…",
        "GLOSSARY_SAVE": "Speichern unter…",
        "GLOSSARY_CAPTION": "Das Glossar wird jeder Anfrage beigelegt und in der Ausgabe geprüft; ein nicht verwendeter Begriff landet in der Prüfliste. Zeilen ohne Quellbegriff werden ignoriert.",
        "GLOSSARY_TABLE_TIP": "Zum Bearbeiten doppelklicken; Zeilen hinzufügen oder löschen.",
        "GLOSSARY_BAD_FILE": "Diese Datei ist kein JSON-Objekt: {\"Quellbegriff\": \"Zielbegriff\"} erwartet.",
        "GLOSSARY_EDIT": "Bearbeiten…",
        "BAR_TOGGLE": "Zur kleinen Leiste wechseln",
        "BAR_TOGGLE_HINT": "Blendet das Fenster aus und führt den Lauf in der schwebenden Leiste fort; „Zurück zum Fenster“ holt es zurück.",
        "HELP_TITLE": "Hilfe",
        "TWEAKS_BROWSE": "Durchsuchen…",
        "TWEAKS_GLOSSARY_TIP": "JSON-Glossardatei wählen: {\"Quellbegriff\": \"Zielbegriff\"}",
        "TWEAKS_GLOSSARY_FILTER": "Glossar (*.json *.csv *.tsv *.txt);;JSON (*.json);;Tabelle (*.csv *.tsv);;Alle Dateien (*)",
        "WELCOME_SHOW": "Begrüßung anzeigen",
        "FLOAT_FOLD": "Einklappen",
        "FLOAT_EXPAND": "Ausklappen",
        "STATUS_VERIFYING": "Ausgabe wird geprüft…",
        "STATUS_CANCELLED": "Abgebrochen",
        "FLOAT_WAITING": "Wird vorbereitet…",
        "FLOAT_PAUSE": "Pausieren",
        "FLOAT_RESUME": "Fortsetzen",
        "FLOAT_RESTORE": "Zum Fenster",
        "FLOAT_DONE": "Fertig",
        "FLOAT_FAILED": "Fehlgeschlagen",
        "FLOAT_SEGMENTS": "{done}/{total} Abschnitte",
        "MENU_RENAME_GROUP": "Gruppe umbenennen",
        "MENU_UNGROUP_ALL": "Gruppe auflösen",
        "MENU_LEAVE_GROUP": "Aus Gruppe nehmen",
        "MENU_TEST_CONNECTION": "Verbindung testen",
        "MENU_DELETE": "Löschen",
        "APP_TITLE": "LayoutKeep",
        "APP_SUBTITLE": "Layout-Erhaltene Dokumenten- und E-Book-Übersetzer",
        "THEME_TOGGLE": "Thema wechseln",
        "LIGHT_MODE": "Heller Modus",
        "DARK_MODE": "Dunkler Modus",
        "UI_LANG_LABEL": "Benutzeroberfläche",
        "STEP_SETUP": "1. Dokument & Format",
        "SETTINGS_CARD_TITLE": "Dokumenteinstellungen",
        "STEP_PROGRESS": "2. Übersetzungsfortschritt",
        "STEP_REVIEW": "3. Abgeschlossen",
        "INPUT_FILE_LABEL": "Eingabedatei",
        "OUTPUT_FILE_LABEL": "Ausgabedatei",
        "OUTPUT_FORMAT_LABEL": "Ausgabeformat",
        "SOURCE_LANG_LABEL": "Ausgangssprache",
        "TARGET_LANG_LABEL": "Zielsprache",
        "LANGS_LABEL": "Sprachen",
        "PROVIDER_LABEL": "Übersetzungsanbieter",
        "PROVIDER_SETTINGS_BTN": "Anbieter-Einstellungen…",
        "OPEN_OUTPUT_BTN": "Ausgabe öffnen",
        "SHOW_IN_FOLDER_BTN": "Im Ordner anzeigen",
        "BACK_TO_SETUP_BTN": "Neue Übersetzung",
        "OUTPUT_MISSING": "Ausgabedatei nicht gefunden:",
        "OUTPUT_READY": "Ausgabe:",
        "START_TRANSLATION_BTN": "Übersetzung starten",
        "COMPLETION_TITLE": "Übersetzung abgeschlossen",
        "TWEAKS_TITLE": "Erweiterte Einstellungen",
        "PROFILE_LABEL": "Voreinstellung",
        "PROFILE_CUSTOM": "Benutzerdefiniert (manuell)",
        "PROFILE_DRAFT": "Schneller Entwurf (7 Anfragen, kleinere Schrift)",
        "PROFILE_QUALITY": "Publikationsqualität (2 Anfragen, gemessene Schwellen)",
        "PROFILE_HINT": "Eine Voreinstellung ändert mehrere Werte zusammen; danach können Sie jeden einzeln bearbeiten. Ein laufender Auftrag behält seine Werte - ein stückweiser Kommandozeilenlauf liest sie jedoch für jedes neue Stück erneut, daher während eines langen Laufs nicht ändern.",
        "TWEAKS_TAB_BASIC": "Allgemein",
        "TWEAKS_TAB_ADVANCED": "Entwickler",
        "TWEAKS_RESET": "Standardwerte",
        "TWEAKS_MENU": "Erweiterte Einstellungen…",
        "TWEAKS_FOOTER": "Änderungen gelten sofort; kein Neustart nötig. Ein laufender Auftrag behält seine Startwerte.",
        "TWEAKS_ADVANCED_BANNER": "Ein falscher Wert erzeugt hier keinen Fehler - er verschlechtert die Ausgabe unbemerkt. Jeder Eintrag nennt die Folge.",
        "ERR_NO_API_KEY": "DeepL benötigt einen API-Schlüssel. Geben Sie ihn in den Anbietereinstellungen ein (kostenlose Schlüssel enden auf ':fx').",
        "STATUS_PAUSING": "wird angehalten… (nach der laufenden Anfrage)",
        "STATUS_PAUSED": "angehalten",
        "STATUS_RESUMING": "wird fortgesetzt…",
        "PROGRESS_FLAGS": "{count} Segmente markiert",
        "ETA_CALCULATING": "Wird berechnet…",
        "ETA_ALMOST": "Fast fertig",
        "ETA_MEASURING": "Wird gemessen…",
        "ETA_SECONDS": "noch ~{s}s",
        "ETA_MINUTES": "noch ~{m} Min {s}s",
        "ETA_MINUTES_ONLY": "noch ~{m} Min",
        "ETA_HOURS": "noch ~{h} Std {m} Min",
        "ETA_HOURS_ONLY": "noch ~{h} Std",
        "ETA_SPEED": "~{v} Zeichen/s",
        "PROGRESS_SEGMENTS": "{done}/{total} Segmente übersetzt ({pct} %)",
        "PROGRESS_MEMORY_HITS": "Speicher-Treffer: {hits}/{total} ({rate})",
        "PROGRESS_BATCH_LIMIT": "Erwartete Obergrenze: {s}s",
        "ERROR_TIMEOUT": "Der Server ({url}) hat nicht innerhalb von {s} Sekunden geantwortet.\nDas Laden eines großen lokalen Modells kann Minuten dauern; versuchen Sie es erneut, wenn der Server bereit ist, oder erhöhen Sie die Zeitüberschreitung in den Anbietereinstellungen.",
        "ERROR_CONNECTION": "{url} ist nicht erreichbar: {exc}\nPrüfen Sie, ob der LM-Studio-Server (Port 1234) oder Ollama (Port 11434) läuft und der Servermodus aktiv ist.",
        "ERROR_NO_TEXT": "Im Dokument wurde kein übersetzbarer Text gefunden.",
        "STATUS_REPEATS_UNIFIED": "{n} wiederholte Segmente wurden zu einer Übersetzung je Quelle zusammengeführt",
        "REVIEW_FIT_FAILED": "die Übersetzung passte nicht in ihren Rahmen, auch nach Verkleinerung nicht",
        "PROGRESS_PREVIEW_SOURCE": "Quelle",
        "PROGRESS_PREVIEW_TARGET": "Übersetzung",
        "COMPLETION_STATS_TITLE": "Prozess",
        "COMPLETION_OUTPUT_TITLE": "Ausgabedatei",
        "COMPLETION_SEGMENTS": "{done} / {total} Segmente übersetzt ({pct} %)",
        "COMPLETION_SPEED": "Durchschnittliche Geschwindigkeit: {speed} Zeichen/s",
        "COMPLETION_FIDELITY": "Layouttreue: {pct} %",
        "COMPLETION_DURATION": "Gesamtzeit: {duration}",
        "COMPLETION_FLAGGED": "{count} Segmente sollten geprüft werden",
        "REVIEW_BOX_CRUSHED": "die Box wurde gekürzt, um den nächsten Block freizuhalten; der Text passt nicht hinein",
        "COMPLETION_FLAGGED_BOX": "{count} davon sind gekürzte Boxen, kein langer Text",
        "COMPLETION_VERIFY_CLEAN": "Prüfung: keine Verluste in der Ausgabe gefunden",
        "COMPLETION_VERIFY_REPAIRED": "Prüfung: {count} Segmente durch erneute Anfrage korrigiert",
        "COMPLETION_VERIFY_REMAINING": "Prüfung: {count} Verluste zur Prüfung markiert ({kinds})",
        "VERIFY_L1": "Seitenzahl abweichend",
        "VERIFY_L2": "nicht übersetzt",
        "VERIFY_L3": "nicht auf die Seite geschrieben",
        "VERIFY_L4": "außerhalb der Seite",
        "VERIFY_L5": "Markup durchgesickert",
        "VERIFY_L6": "Zahlen verloren",
        "VERIFY_L7": "über anderen Text geschrieben",
        "VERIFY_L8": "unübersetzter Text verschoben",
        "VERIFY_L9": "Buchstaben aus einem anderen Alphabet",
        "COMPLETION_SUBTITLE": "Ihr Dokument wurde erfolgreich übersetzt. Öffnen Sie die Ausgabe, zeigen Sie sie im Ordner an oder starten Sie eine neue Übersetzung.",
        "BROWSE_BTN": "Durchsuchen…",
        "DROPZONE_PROMPT": "Datei hierher ziehen oder durchsuchen",
        "DROPZONE_HINT": "Unterstützt: PDF, EPUB, DOCX, PNG, JPG, WEBP, LKPROJ",
        "DROPZONE_FILE_SELECTED": "Ausgewählte Datei:",
        "DROPZONE_CLEAR": "Entfernen",
        "EPUB_LOCK_REASON": "EPUB-Ausgabe aus diesem Quellformat ist noch nicht gemessen und bestätigt",
        "DOCX_LOCK_REASON": "Word-Ausgabe aus diesem Quellformat ist noch nicht gemessen und bestätigt",
        "HTML_LOCK_REASON": "HTML-Ausgabe aus diesem Quellformat ist noch nicht gemessen und bestätigt",
        "IMAGE_LOCK_REASON": "Bildausgabe aus diesem Quellformat ist noch nicht gemessen und bestätigt",
        "LOCKED_SUFFIX": "gesperrt",
        "LOCKED_TITLE": "Diese Umwandlung ist noch nicht bereit",
        "LOCKED_BODY": "Offen sind: PDF→PDF/Word/EPUB/HTML, EPUB→EPUB/Word/HTML/PNG, Word→Word/EPUB/HTML/PNG/PDF, PNG→Word. Die übrigen Ziele wurden gemessen und verlieren still einen Teil des Dokuments; sie werden freigegeben, sobald sie tragen.\n\nDie Messungen: docs/ENGINE-ARCHITECTURE.md",
        "LOCKED_SOURCE_BODY": "Für diesen Dateityp ist noch kein Ziel offen. Offen sind: PDF→PDF/Word/EPUB/HTML, EPUB→EPUB/Word/HTML/PNG, Word→Word/EPUB/HTML/PNG/PDF, PNG→Word.\n\nDie Messungen: docs/ENGINE-ARCHITECTURE.md",
        "FORMAT_SAME": "Wie Ausgangsformat",
        "FORMAT_PDF": "PDF-Dokument (.pdf)",
        "FORMAT_HTML": "HTML-Webseite (.html)",
        "FORMAT_EPUB": "EPUB E-Book (.epub)",
        "FORMAT_DOCX": "Word-Dokument (.docx)",
        "FORMAT_PNG": "PNG-Bild (.png)",
        "FORMAT_JPG": "JPG-Bild (.jpg)",
        "RANGE_LABEL": "Bereich",
        "RANGE_ALL": "Gesamtes Dokument",
        "RANGE_CUSTOM": "Benutzerdefinierter Seitenbereich",
        "RANGE_PLACEHOLDER": "z.B. 1-5, 8",
        "RANGE_HINT": "Nur dieser Bereich wird übersetzt, und die Ausgabe enthält nur diese Seiten (das Projekt behält das ganze Dokument).",
        "DUAL_LABEL": "Zweisprachiges PDF",
        "DUAL_OFF": "Aus",
        "DUAL_SIDE": "Nebeneinander (Quelle links)",
        "DUAL_ALTERNATE": "Abwechselnde Seiten",
        "DUAL_HINT": "Neben der übersetzten Datei wird ein zweites PDF geschrieben, das auch die Quelle enthält. Prüfung und Hauptausgabe bleiben unverändert.",
        "CLOSE_BTN": "Schließen",
        "PROGRESS_TITLE": "Übersetzung läuft…",
        "STATUS_READING": "Dokument wird gelesen und analysiert…",
        "STATUS_TRANSLATING": "Segmente werden übersetzt…",
        "STATUS_FITTING": "Typografie und Layout werden berechnet…",
        "STATUS_WRITING": "Ausgabedatei wird gespeichert…",
        "STATUS_FINISHED": "Vorgang erfolgreich abgeschlossen!",
        "CANCEL_BTN": "Abbrechen",
        "PAUSE_BTN": "Pausieren",
        "RESUME_BTN": "Fortsetzen",
        "MEMORY_STATS_LABEL": "Übersetzungsspeicher:",
        "PROGRESS_ELAPSED": "Verstrichen:",
        "PROGRESS_REMAINING": "Verbleibend:",
        "PROGRESS_SPEED": "Geschwindigkeit:",
        "PROGRESS_MODEL_LABEL": "Aktives Modell:",
        "PROGRESS_ACTIVE_TITLE": "Aktives Segment:",
        "PROGRESS_CHARS_LABEL": "Zeichen:",
        "PROGRESS_SEGMENTS_LABEL": "Segmente:",
        "PROGRESS_MEMORY_SAVED": "TM-Ersparnis:",
        "PROGRESS_WAITING_SERVER": "Warte auf Modellantwort…",
        "PROGRESS_STARTING": "Startet…",
        "PROGRESS_PAUSED": "Pausiert",
        "PROGRESS_RESUMING": "Wird fortgesetzt…",
        "PROGRESS_CANCELLED": "Abgebrochen",
        "ERR_MISSING_INPUT": "Keine Eingabedatei ausgewählt.",
        "ERR_INPUT_NOT_FOUND": "Eingabedatei nicht gefunden:\n",
        "ERR_MISSING_OUTPUT": "Keine Ausgabedatei angegeben.",
        "ERR_OUTPUT_DIR_NOT_FOUND": "Ausgabeordner nicht gefunden:\n",
        "ERR_NO_MODEL": "Kein Modell ausgewählt. Bitte Modell in Einstellungen wählen.",
        "ERR_INCOMPLETE_INFO": "Unvollständige Informationen",
    },
}


class UIStringsMeta(type):
    # Dinamik arayüz metni çözümleme üst sınıfı / Metaclass for dynamic i18n resolution
    def __getattr__(cls, key: str) -> str:
        return cls.get(key)


class UIStrings(metaclass=UIStringsMeta):
    # Çok dilli kullanıcı arayüzü metin yöneticisi / Multilingual UI strings manager
    #: English by default: the project is published in English, so a first run has to be
    #: readable to anyone who opens it. Turkish is one click away in the header and the choice
    #: is remembered.
    _current_lang: str = "en"
    SUPPORTED_LANGUAGES: tuple[tuple[str, str], ...] = (
        ("tr", "Türkçe"),
        ("en", "English"),
        ("de", "Deutsch"),
    )

    @classmethod
    def set_language(cls, lang: str) -> None:
        # Aktif arayüz dilini ayarlar / Sets active UI language
        if lang in _TRANSLATIONS:
            cls._current_lang = lang

    @classmethod
    def get_language(cls) -> str:
        # Aktif arayüz dil kodunu döndürür / Returns active UI language code
        return cls._current_lang

    @classmethod
    def get(cls, key: str) -> str:
        # Anahtara ve aktif dile göre metni döndürür / Returns string for key in active language
        # A key missing from the active language falls back to English, not Turkish: this is
        # what a user of the German or English interface would see, and a stray Turkish string
        # in an otherwise English window reads as a bug rather than as a translation gap.
        active = _TRANSLATIONS.get(cls._current_lang, _TRANSLATIONS["en"])
        if key in active:
            return active[key]
        return _TRANSLATIONS["en"].get(key, key)
