"""User interface text strings and i18n management for LayoutKeep.

Kullanıcı arayüzünde gösterilen tüm çok dilli metinlerin merkezi tanım ve yönetim dosyası.
"""

from __future__ import annotations

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "tr": {
        "MENU_RENAME_GROUP": "Grubu yeniden adlandır",
        "MENU_UNGROUP_ALL": "Grubu dağıt",
        "MENU_LEAVE_GROUP": "Gruptan çıkar",
        "MENU_TEST_CONNECTION": "Bağlantıyı sına",
        "MENU_DELETE": "Sil",
        "APP_TITLE": "LayoutKeep",
        "APP_SUBTITLE": "Düzen Koruyan Belge ve E-Kitap Çevirmeni",
        "THEME_TOGGLE": "Temayı Değiştir",
        "LIGHT_MODE": "Açık Tema",
        "DARK_MODE": "Koyu Tema",
        "UI_LANG_LABEL": "Arayüz Dili",
        "STEP_SETUP": "1. Belge & Format",
        "SETTINGS_CARD_TITLE": "Belge Ayarları",
        "STEP_PROGRESS": "2. Çeviri Süreci",
        "STEP_REVIEW": "3. Tamamlandı",
        "INPUT_FILE_LABEL": "Girdi Dosyası",
        "OUTPUT_FILE_LABEL": "Çıktı Dosyası",
        "OUTPUT_FORMAT_LABEL": "Çıktı Formatı",
        "SOURCE_LANG_LABEL": "Kaynak Dil",
        "TARGET_LANG_LABEL": "Hedef Dil",
        "LANGS_LABEL": "Diller",
        "PROVIDER_LABEL": "Çeviri Sağlayıcısı",
        "PROVIDER_SETTINGS_BTN": "Sağlayıcı Ayarları…",
        "OPEN_OUTPUT_BTN": "Çıktıyı Aç",
        "SHOW_IN_FOLDER_BTN": "Klasörde Göster",
        "BACK_TO_SETUP_BTN": "Yeni Çeviri",
        "OUTPUT_MISSING": "Çıktı dosyası bulunamadı:",
        "OUTPUT_READY": "Çıktı:",
        "START_TRANSLATION_BTN": "Çeviriyi Başlat",
        "COMPLETION_TITLE": "Çeviri Tamamlandı",
        "TWEAKS_TITLE": "Gelişmiş Ayarlar",
        "TWEAKS_TAB_BASIC": "Genel",
        "TWEAKS_TAB_ADVANCED": "Geliştirici",
        "TWEAKS_RESET": "Varsayılanlara Dön",
        "TWEAKS_MENU": "Gelişmiş Ayarlar…",
        "TWEAKS_FOOTER": "Değişiklikler hemen geçerli olur; uygulamayı yeniden başlatmanız gerekmez. Süren bir çeviri başladığı değerlerle devam eder.",
        "TWEAKS_ADVANCED_BANNER": "Buradaki değerler yanlış ayarlandığında hata vermez - çıktıyı sessizce kötüleştirir. Her birinin altında neyin bozulacağı yazıyor.",
        "ERR_NO_API_KEY": "DeepL için API anahtarı gerekli. Sağlayıcı Ayarları'ndan girin (ücretsiz anahtarlar ':fx' ile biter).",
        "STATUS_PAUSING": "duraklatılıyor… (süren istek bitince)",
        "STATUS_PAUSED": "duraklatıldı",
        "STATUS_RESUMING": "çeviriye devam ediliyor…",
        "PROGRESS_FLAGS": "{count} segment işaretlendi",
        "PROGRESS_PREVIEW_SOURCE": "Kaynak",
        "PROGRESS_PREVIEW_TARGET": "Çeviri",
        "COMPLETION_STATS_TITLE": "Proses",
        "COMPLETION_OUTPUT_TITLE": "Çıktı Dosyası",
        "COMPLETION_SEGMENTS": "{done} / {total} segment çevrildi (%{pct})",
        "COMPLETION_SPEED": "Ortalama hız: {speed} kar/sn",
        "COMPLETION_FIDELITY": "Düzen uyumu: %{pct}",
        "COMPLETION_DURATION": "Toplam süre: {duration}",
        "COMPLETION_FLAGGED": "{count} segment gözden geçirilmeli",
        "COMPLETION_SUBTITLE": "Belgeniz başarıyla çevrildi. Çıktıyı açabilir, klasörde gösterebilir veya yeni bir çeviri başlatabilirsiniz.",
        "BROWSE_BTN": "Gözat…",
        "DROPZONE_PROMPT": "Dosyayı buraya sürükleyin veya gözatarak seçin",
        "DROPZONE_HINT": "Desteklenenler: PDF, EPUB, DOCX, PNG, JPG, WEBP, LKPROJ",
        "DROPZONE_FILE_SELECTED": "Seçilen dosya:",
        "DROPZONE_CLEAR": "Kaldır",
        "FORMAT_SAME": "Kaynak Format ile Aynı",
        "FORMAT_PDF": "PDF Belgesi (.pdf)",
        "FORMAT_HTML": "HTML Web Sayfası (.html)",
        "FORMAT_EPUB": "EPUB E-Kitap (.epub)",
        "FORMAT_DOCX": "Word Belgesi (.docx)",
        "FORMAT_PNG": "PNG Görsel (.png)",
        "FORMAT_JPG": "JPG Görsel (.jpg)",
        "RANGE_LABEL": "Aralık",
        "RANGE_ALL": "Tüm Belge",
        "RANGE_CUSTOM": "Sayfa / Bölüm Aralığı",
        "RANGE_PLACEHOLDER": "Örn: 1-5, 8",
        "PROGRESS_TITLE": "Çeviri İşleniyor…",
        "STATUS_READING": "Belge okunuyor ve ayrıştırılıyor…",
        "STATUS_TRANSLATING": "Metinler çevriliyor…",
        "STATUS_FITTING": "Tipografi ve yerleşim hesaplanıyor…",
        "STATUS_WRITING": "Çıktı dosyası kaydediliyor…",
        "STATUS_FINISHED": "İşlem başarıyla tamamlandı!",
        "CANCEL_BTN": "İptal Et",
        "PAUSE_BTN": "Duraklat",
        "RESUME_BTN": "Devam Et",
        "MEMORY_STATS_LABEL": "Bellek Durumu:",
        "PROGRESS_ELAPSED": "Geçen:",
        "PROGRESS_REMAINING": "Kalan:",
        "PROGRESS_SPEED": "Hız:",
        "PROGRESS_MODEL_LABEL": "Aktif Model:",
        "PROGRESS_ACTIVE_TITLE": "İşlenen Segment:",
        "PROGRESS_CHARS_LABEL": "Karakter:",
        "PROGRESS_SEGMENTS_LABEL": "Segment:",
        "PROGRESS_MEMORY_SAVED": "TM Tasarrufu:",
        "PROGRESS_WAITING_SERVER": "Model yanıtı bekleniyor…",
        "PROGRESS_STARTING": "Başlatılıyor…",
        "PROGRESS_PAUSED": "Duraklatıldı",
        "PROGRESS_RESUMING": "Devam ediliyor…",
        "PROGRESS_CANCELLED": "İptal edildi",
        "ERR_MISSING_INPUT": "Girdi dosyası seçilmedi.",
        "ERR_INPUT_NOT_FOUND": "Girdi dosyası bulunamadı:\n",
        "ERR_MISSING_OUTPUT": "Çıktı dosyası belirtilmedi.",
        "ERR_OUTPUT_DIR_NOT_FOUND": "Çıktı klasörü bulunamadı:\n",
        "ERR_NO_MODEL": "Sağlayıcı için model seçilmedi. Ayarlardan model belirleyin.",
        "ERR_INCOMPLETE_INFO": "Eksik Bilgi",
    },
    "en": {
        "MENU_RENAME_GROUP": "Rename group",
        "MENU_UNGROUP_ALL": "Break up group",
        "MENU_LEAVE_GROUP": "Take out of group",
        "MENU_TEST_CONNECTION": "Test connection",
        "MENU_DELETE": "Delete",
        "APP_TITLE": "LayoutKeep",
        "APP_SUBTITLE": "Layout-Preserving Document & E-Book Translator",
        "THEME_TOGGLE": "Toggle Theme",
        "LIGHT_MODE": "Light Mode",
        "DARK_MODE": "Dark Mode",
        "UI_LANG_LABEL": "UI Language",
        "STEP_SETUP": "1. Document & Format",
        "SETTINGS_CARD_TITLE": "Document Settings",
        "STEP_PROGRESS": "2. Translation Progress",
        "STEP_REVIEW": "3. Completed",
        "INPUT_FILE_LABEL": "Input File",
        "OUTPUT_FILE_LABEL": "Output File",
        "OUTPUT_FORMAT_LABEL": "Output Format",
        "SOURCE_LANG_LABEL": "Source Language",
        "TARGET_LANG_LABEL": "Target Language",
        "LANGS_LABEL": "Languages",
        "PROVIDER_LABEL": "Translation Provider",
        "PROVIDER_SETTINGS_BTN": "Provider Settings…",
        "OPEN_OUTPUT_BTN": "Open Output",
        "SHOW_IN_FOLDER_BTN": "Show in Folder",
        "BACK_TO_SETUP_BTN": "New Translation",
        "OUTPUT_MISSING": "Output file not found:",
        "OUTPUT_READY": "Output:",
        "START_TRANSLATION_BTN": "Start Translation",
        "COMPLETION_TITLE": "Translation Completed",
        "TWEAKS_TITLE": "Advanced Settings",
        "TWEAKS_TAB_BASIC": "General",
        "TWEAKS_TAB_ADVANCED": "Developer",
        "TWEAKS_RESET": "Restore Defaults",
        "TWEAKS_MENU": "Advanced Settings…",
        "TWEAKS_FOOTER": "Changes take effect immediately; no restart needed. A job already running keeps the values it started with.",
        "TWEAKS_ADVANCED_BANNER": "A wrong value here does not raise an error - it quietly makes the output worse. Each entry says what breaks.",
        "ERR_NO_API_KEY": "DeepL needs an API key. Enter it in Provider Settings (free keys end in ':fx').",
        "STATUS_PAUSING": "pausing… (after the current request)",
        "STATUS_PAUSED": "paused",
        "STATUS_RESUMING": "resuming…",
        "PROGRESS_FLAGS": "{count} segments flagged",
        "PROGRESS_PREVIEW_SOURCE": "Source",
        "PROGRESS_PREVIEW_TARGET": "Translation",
        "COMPLETION_STATS_TITLE": "Process",
        "COMPLETION_OUTPUT_TITLE": "Output file",
        "COMPLETION_SEGMENTS": "{done} / {total} segments translated ({pct}%)",
        "COMPLETION_SPEED": "Average speed: {speed} chars/s",
        "COMPLETION_FIDELITY": "Layout fidelity: {pct}%",
        "COMPLETION_DURATION": "Total time: {duration}",
        "COMPLETION_FLAGGED": "{count} segments need review",
        "COMPLETION_SUBTITLE": "Your document was translated successfully. Open the output, show it in a folder, or start a new translation.",
        "BROWSE_BTN": "Browse…",
        "DROPZONE_PROMPT": "Drag & drop a file here or browse to select",
        "DROPZONE_HINT": "Supported: PDF, EPUB, DOCX, PNG, JPG, WEBP, LKPROJ",
        "DROPZONE_FILE_SELECTED": "Selected file:",
        "DROPZONE_CLEAR": "Clear",
        "FORMAT_SAME": "Same as Source",
        "FORMAT_PDF": "PDF Document (.pdf)",
        "FORMAT_HTML": "HTML Webpage (.html)",
        "FORMAT_EPUB": "EPUB E-Book (.epub)",
        "FORMAT_DOCX": "Word Document (.docx)",
        "FORMAT_PNG": "PNG Image (.png)",
        "FORMAT_JPG": "JPG Image (.jpg)",
        "RANGE_LABEL": "Range",
        "RANGE_ALL": "Whole Document",
        "RANGE_CUSTOM": "Page / Section Range",
        "RANGE_PLACEHOLDER": "e.g. 1-5, 8",
        "PROGRESS_TITLE": "Translating Document…",
        "STATUS_READING": "Reading and parsing document…",
        "STATUS_TRANSLATING": "Translating text segments…",
        "STATUS_FITTING": "Calculating typography and fitting…",
        "STATUS_WRITING": "Saving output file…",
        "STATUS_FINISHED": "Process completed successfully!",
        "CANCEL_BTN": "Cancel",
        "PAUSE_BTN": "Pause",
        "RESUME_BTN": "Resume",
        "MEMORY_STATS_LABEL": "Translation Memory:",
        "PROGRESS_ELAPSED": "Elapsed:",
        "PROGRESS_REMAINING": "Remaining:",
        "PROGRESS_SPEED": "Speed:",
        "PROGRESS_MODEL_LABEL": "Active Model:",
        "PROGRESS_ACTIVE_TITLE": "Active Segment:",
        "PROGRESS_CHARS_LABEL": "Characters:",
        "PROGRESS_SEGMENTS_LABEL": "Segments:",
        "PROGRESS_MEMORY_SAVED": "TM Savings:",
        "PROGRESS_WAITING_SERVER": "Waiting for model response…",
        "PROGRESS_STARTING": "Starting…",
        "PROGRESS_PAUSED": "Paused",
        "PROGRESS_RESUMING": "Resuming…",
        "PROGRESS_CANCELLED": "Cancelled",
        "ERR_MISSING_INPUT": "No input file selected.",
        "ERR_INPUT_NOT_FOUND": "Input file not found:\n",
        "ERR_MISSING_OUTPUT": "No output file specified.",
        "ERR_OUTPUT_DIR_NOT_FOUND": "Output folder not found:\n",
        "ERR_NO_MODEL": "No model selected for provider. Please select a model in settings.",
        "ERR_INCOMPLETE_INFO": "Incomplete Information",
    },
    "de": {
        "MENU_RENAME_GROUP": "Gruppe umbenennen",
        "MENU_UNGROUP_ALL": "Gruppe auflösen",
        "MENU_LEAVE_GROUP": "Aus Gruppe nehmen",
        "MENU_TEST_CONNECTION": "Verbindung testen",
        "MENU_DELETE": "Löschen",
        "APP_TITLE": "LayoutKeep",
        "APP_SUBTITLE": "Layout-Erhaltene Dokumenten- und E-Book-Übersetzer",
        "THEME_TOGGLE": "Thema wechseln",
        "LIGHT_MODE": "Heller Modus",
        "DARK_MODE": "Dunkler Modus",
        "UI_LANG_LABEL": "Benutzeroberfläche",
        "STEP_SETUP": "1. Dokument & Format",
        "SETTINGS_CARD_TITLE": "Dokumenteinstellungen",
        "STEP_PROGRESS": "2. Übersetzungsfortschritt",
        "STEP_REVIEW": "3. Abgeschlossen",
        "INPUT_FILE_LABEL": "Eingabedatei",
        "OUTPUT_FILE_LABEL": "Ausgabedatei",
        "OUTPUT_FORMAT_LABEL": "Ausgabeformat",
        "SOURCE_LANG_LABEL": "Ausgangssprache",
        "TARGET_LANG_LABEL": "Zielsprache",
        "LANGS_LABEL": "Sprachen",
        "PROVIDER_LABEL": "Übersetzungsanbieter",
        "PROVIDER_SETTINGS_BTN": "Anbieter-Einstellungen…",
        "OPEN_OUTPUT_BTN": "Ausgabe öffnen",
        "SHOW_IN_FOLDER_BTN": "Im Ordner anzeigen",
        "BACK_TO_SETUP_BTN": "Neue Übersetzung",
        "OUTPUT_MISSING": "Ausgabedatei nicht gefunden:",
        "OUTPUT_READY": "Ausgabe:",
        "START_TRANSLATION_BTN": "Übersetzung starten",
        "COMPLETION_TITLE": "Übersetzung abgeschlossen",
        "TWEAKS_TITLE": "Erweiterte Einstellungen",
        "TWEAKS_TAB_BASIC": "Allgemein",
        "TWEAKS_TAB_ADVANCED": "Entwickler",
        "TWEAKS_RESET": "Standardwerte",
        "TWEAKS_MENU": "Erweiterte Einstellungen…",
        "TWEAKS_FOOTER": "Änderungen gelten sofort; kein Neustart nötig. Ein laufender Auftrag behält seine Startwerte.",
        "TWEAKS_ADVANCED_BANNER": "Ein falscher Wert erzeugt hier keinen Fehler - er verschlechtert die Ausgabe unbemerkt. Jeder Eintrag nennt die Folge.",
        "ERR_NO_API_KEY": "DeepL benötigt einen API-Schlüssel. Geben Sie ihn in den Anbietereinstellungen ein (kostenlose Schlüssel enden auf ':fx').",
        "STATUS_PAUSING": "wird angehalten… (nach der laufenden Anfrage)",
        "STATUS_PAUSED": "angehalten",
        "STATUS_RESUMING": "wird fortgesetzt…",
        "PROGRESS_FLAGS": "{count} Segmente markiert",
        "PROGRESS_PREVIEW_SOURCE": "Quelle",
        "PROGRESS_PREVIEW_TARGET": "Übersetzung",
        "COMPLETION_STATS_TITLE": "Prozess",
        "COMPLETION_OUTPUT_TITLE": "Ausgabedatei",
        "COMPLETION_SEGMENTS": "{done} / {total} Segmente übersetzt ({pct} %)",
        "COMPLETION_SPEED": "Durchschnittliche Geschwindigkeit: {speed} Zeichen/s",
        "COMPLETION_FIDELITY": "Layouttreue: {pct} %",
        "COMPLETION_DURATION": "Gesamtzeit: {duration}",
        "COMPLETION_FLAGGED": "{count} Segmente sollten geprüft werden",
        "COMPLETION_SUBTITLE": "Ihr Dokument wurde erfolgreich übersetzt. Öffnen Sie die Ausgabe, zeigen Sie sie im Ordner an oder starten Sie eine neue Übersetzung.",
        "BROWSE_BTN": "Durchsuchen…",
        "DROPZONE_PROMPT": "Datei hierher ziehen oder durchsuchen",
        "DROPZONE_HINT": "Unterstützt: PDF, EPUB, DOCX, PNG, JPG, WEBP, LKPROJ",
        "DROPZONE_FILE_SELECTED": "Ausgewählte Datei:",
        "DROPZONE_CLEAR": "Entfernen",
        "FORMAT_SAME": "Wie Ausgangsformat",
        "FORMAT_PDF": "PDF-Dokument (.pdf)",
        "FORMAT_HTML": "HTML-Webseite (.html)",
        "FORMAT_EPUB": "EPUB E-Book (.epub)",
        "FORMAT_DOCX": "Word-Dokument (.docx)",
        "FORMAT_PNG": "PNG-Bild (.png)",
        "FORMAT_JPG": "JPG-Bild (.jpg)",
        "RANGE_LABEL": "Bereich",
        "RANGE_ALL": "Gesamtes Dokument",
        "RANGE_CUSTOM": "Benutzerdefinierter Seitenbereich",
        "RANGE_PLACEHOLDER": "z.B. 1-5, 8",
        "PROGRESS_TITLE": "Übersetzung läuft…",
        "STATUS_READING": "Dokument wird gelesen und analysiert…",
        "STATUS_TRANSLATING": "Segmente werden übersetzt…",
        "STATUS_FITTING": "Typografie und Layout werden berechnet…",
        "STATUS_WRITING": "Ausgabedatei wird gespeichert…",
        "STATUS_FINISHED": "Vorgang erfolgreich abgeschlossen!",
        "CANCEL_BTN": "Abbrechen",
        "PAUSE_BTN": "Pausieren",
        "RESUME_BTN": "Fortsetzen",
        "MEMORY_STATS_LABEL": "Übersetzungsspeicher:",
        "PROGRESS_ELAPSED": "Verstrichen:",
        "PROGRESS_REMAINING": "Verbleibend:",
        "PROGRESS_SPEED": "Geschwindigkeit:",
        "PROGRESS_MODEL_LABEL": "Aktives Modell:",
        "PROGRESS_ACTIVE_TITLE": "Aktives Segment:",
        "PROGRESS_CHARS_LABEL": "Zeichen:",
        "PROGRESS_SEGMENTS_LABEL": "Segmente:",
        "PROGRESS_MEMORY_SAVED": "TM-Ersparnis:",
        "PROGRESS_WAITING_SERVER": "Warte auf Modellantwort…",
        "PROGRESS_STARTING": "Startet…",
        "PROGRESS_PAUSED": "Pausiert",
        "PROGRESS_RESUMING": "Wird fortgesetzt…",
        "PROGRESS_CANCELLED": "Abgebrochen",
        "ERR_MISSING_INPUT": "Keine Eingabedatei ausgewählt.",
        "ERR_INPUT_NOT_FOUND": "Eingabedatei nicht gefunden:\n",
        "ERR_MISSING_OUTPUT": "Keine Ausgabedatei angegeben.",
        "ERR_OUTPUT_DIR_NOT_FOUND": "Ausgabeordner nicht gefunden:\n",
        "ERR_NO_MODEL": "Kein Modell ausgewählt. Bitte Modell in Einstellungen wählen.",
        "ERR_INCOMPLETE_INFO": "Unvollständige Informationen",
    },
}


class UIStringsMeta(type):
    # Dinamik arayüz metni çözümleme üst sınıfı / Metaclass for dynamic i18n resolution
    def __getattr__(cls, key: str) -> str:
        return cls.get(key)


class UIStrings(metaclass=UIStringsMeta):
    # Çok dilli kullanıcı arayüzü metin yöneticisi / Multilingual UI strings manager
    #: English by default: the project is published in English, so a first run has to be
    #: readable to anyone who opens it. Turkish is one click away in the header and the choice
    #: is remembered.
    _current_lang: str = "en"
    SUPPORTED_LANGUAGES: tuple[tuple[str, str], ...] = (
        ("tr", "Türkçe"),
        ("en", "English"),
        ("de", "Deutsch"),
    )

    @classmethod
    def set_language(cls, lang: str) -> None:
        # Aktif arayüz dilini ayarlar / Sets active UI language
        if lang in _TRANSLATIONS:
            cls._current_lang = lang

    @classmethod
    def get_language(cls) -> str:
        # Aktif arayüz dil kodunu döndürür / Returns active UI language code
        return cls._current_lang

    @classmethod
    def get(cls, key: str) -> str:
        # Anahtara ve aktif dile göre metni döndürür / Returns string for key in active language
        # A key missing from the active language falls back to English, not Turkish: this is
        # what a user of the German or English interface would see, and a stray Turkish string
        # in an otherwise English window reads as a bug rather than as a translation gap.
        active = _TRANSLATIONS.get(cls._current_lang, _TRANSLATIONS["en"])
        if key in active:
            return active[key]
        return _TRANSLATIONS["en"].get(key, key)
