"""Collect every campaign book's audit, repair rounds and timing into one comparison table.

Reads `_artifacts/campaign/runs/<book>/` (audit.json, repair_history.json, run.log) and writes a
Markdown section that `docs/campaign/REPORT.md` includes. Numbers only - the judgement of what they
mean, and the visual spot checks, are written in the report by hand.

    python tools/audit/campaign_report.py --runs _artifacts/campaign/runs --out docs/campaign/RESULTS.md
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import pymupdf

#: Campaign order, with what makes each book different. Kept here so the table explains itself.
BOOKS = [
    ("architecture", "computer-systems-Architecture", "textbook scan, no text layer"),
    ("electricity_1922", "Electricity in Agriculture (1922)", "old book scan + hidden OCR layer"),
    ("think_python", "Think Python, 2nd ed.", "born-digital textbook, code"),
    ("nist", "NIST SP 800-12 Rev. 1", "born-digital report, contents, tables"),
    ("time_machine", "The Time Machine", "born-digital novel"),
    ("popular_science_1920", "Popular Science Monthly, Jan 1920", "magazine scan, columns, adverts"),
]

LOSSES = ("L1", "L2", "L3", "L4", "L5", "L6")


def _minutes(run_log: Path) -> float | None:
    if not run_log.exists():
        return None
    found = re.findall(r"in ([\d.]+) min", run_log.read_text(encoding="utf-8", errors="replace"))
    return float(found[-1]) if found else None


def _row(runs: Path, key: str, title: str, kind: str) -> str | None:
    work = runs / key
    audit_path = work / "audit.json"
    if not audit_path.exists():
        return None
    audit = json.loads(audit_path.read_text(encoding="utf-8"))
    counts = audit["counts"]
    pages = 0
    output = work / f"{key}.tr.pdf"
    if output.exists():
        with pymupdf.open(str(output)) as doc:
            pages = doc.page_count

    first = None
    rounds = 0
    history_path = work / "repair_history.json"
    if history_path.exists():
        history = json.loads(history_path.read_text(encoding="utf-8"))
        rounds = sum(1 for h in history if "round" in h and h["failing_before"])
        first = next((h["counts"] for h in history if h.get("round") == 1), None)

    def losses(c: dict) -> str:
        return " / ".join(str(c.get(k, 0)) for k in LOSSES)

    minutes = _minutes(work / "run.log")
    return (
        f"| {title} | {kind} | {pages} | {audit['blocks']} | "
        f"{losses(first) if first else losses(counts)} | {rounds} | {losses(counts)} | "
        f"{counts.get('D1', 0)} ({100 * counts.get('D1', 0) / max(audit['blocks'], 1):.0f}%) | "
        f"{counts.get('D2', 0)} | {'**yes**' if audit['lossless'] else 'no'} | "
        f"{minutes if minutes is not None else '-'} |"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs", type=Path, default=Path("_artifacts/campaign/runs"))
    parser.add_argument("--out", type=Path, default=Path("docs/campaign/RESULTS.md"))
    args = parser.parse_args()

    lines = [
        "# Campaign results (generated by tools/audit/campaign_report.py)",
        "",
        "Loss columns are `L1 / L2 / L3 / L4 / L5 / L6` = pages differ / untranslated / dropped by "
        "the writer / off the page / markup leaked / numbers lost. **Lossless** means all six are 0.",
        "D1 = blocks drawn below the readability floor (text present, quality cost). "
        "D2 = short blocks left unchanged, for a human (names or untranslated phrases).",
        "",
        "| book | kind | pages | blocks | losses, first pass | repair rounds | losses, final | D1 | D2 "
        "| lossless | first pass min |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for key, title, kind in BOOKS:
        row = _row(args.runs, key, title, kind)
        lines.append(row if row else f"| {title} | {kind} | not run yet | | | | | | | | |")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
