"""Summarise the held-out measurement: one row per source, as the application translated it.

Reads `_artifacts/heldout/`: `heldout.log` (when each source started), `code_versions.log` (which
commit the frozen worktree held when), and each `runs/<name>/` - its `commit.txt`, the audit of a PDF
run, and the `verify` lines the application printed for every page. Numbers only; what they mean, and the
visual checks against the sources, are written in the journal by hand.

    python tools/audit/heldout_report.py --root _artifacts/heldout --out docs/campaign/HELDOUT.md
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path

_KINDS = ("L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9")
_START = re.compile(r"^\[heldout\] start (\S+) (\d\d:\d\d)")
_SWITCH = re.compile(r"^(\d\d:\d\d)(?::\d\d)? worktree -> (\w+)")
_MENDED = re.compile(r"(\d+) mended by asking again")
_FLAGGED = re.compile(r"^\s+(L\d) [^:]+: (\d+) - flagged for review", re.MULTILINE)
_MINUTES = re.compile(r"in ([\d.]+) min")


def _commit_for(start: str, switches: list[tuple[str, str]], first: str) -> str:
    commit = first
    for when, target in switches:
        if when <= start:
            commit = target
    return commit


def _verification(logs: list[Path]) -> tuple[int, Counter]:
    mended, flagged = 0, Counter()
    for log in logs:
        text = log.read_text(encoding="utf-8", errors="replace")
        mended += sum(int(n) for n in _MENDED.findall(text))
        for kind, count in _FLAGGED.findall(text):
            flagged[kind] += int(count)
    return mended, flagged


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("_artifacts/heldout"))
    parser.add_argument("--out", type=Path, default=Path("docs/campaign/HELDOUT.md"))
    parser.add_argument("--first-commit", default="bad981a")
    args = parser.parse_args()

    starts = dict(
        m.groups() for line in (args.root / "heldout.log").read_text(encoding="utf-8").splitlines()
        if (m := _START.match(line))
    )
    versions = args.root / "code_versions.log"
    switches = [
        m.groups() for line in (versions.read_text(encoding="utf-8").splitlines() if versions.exists() else [])
        if (m := _SWITCH.match(line))
    ]

    rows = [
        "# Held-out measurement (generated by tools/audit/heldout_report.py)",
        "",
        (
            "The application as a user runs it: layout model on, verification on (`--verify-rounds 2`), "
            "no campaign repair. `mended` = segments verification asked for again and got back right; "
            "`flagged` = losses it left flagged for review, by kind. Loss columns are the audit of the "
            "written output, `L1 / ... / L9`."
        ),
        "",
        "| source | commit | pages | blocks | mended | flagged | losses L1-L9 | D1 | lossless | min |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name, start in starts.items():
        work = args.root / "runs" / name
        recorded = work / "commit.txt"
        commit = (
            recorded.read_text(encoding="utf-8").strip() if recorded.exists()
            else _commit_for(start, switches, args.first_commit)
        )
        chunk_logs = sorted((work / "out").glob("t_*.log"))
        mended, flagged = _verification(chunk_logs or [work / "run.log"])
        flagged_text = ", ".join(f"{k} {v}" for k, v in sorted(flagged.items())) or "-"
        audit_path = work / "audit.json"
        if audit_path.exists():
            audit = json.loads(audit_path.read_text(encoding="utf-8"))
            counts = audit["counts"]
            losses = " / ".join(str(counts.get(k, 0)) for k in _KINDS)
            pages = len(list((work / "src").glob("chunk_*.pdf")))
            minutes = _MINUTES.findall((work / "run.log").read_text(encoding="utf-8", errors="replace"))
            rows.append(
                f"| {name} | {commit} | {pages} | {audit['blocks']} | {mended} | {flagged_text} | {losses} | "
                f"{counts.get('D1', 0)} | {'**yes**' if audit['lossless'] else 'no'} | "
                f"{minutes[-1] if minutes else '-'} |"
            )
        else:
            finished = (work / "run.log").exists() and "verify" in (work / "run.log").read_text(
                encoding="utf-8", errors="replace"
            )
            rows.append(
                f"| {name} | {commit} | - | - | {mended} | {flagged_text} | "
                f"{'not a PDF: verification only' if finished else 'running'} | - | - | - |"
            )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print("\n".join(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
